#!/usr/bin/env python3
"""Qwen3.5-2B — runtime-only runner: LOAD the prebuilt unified instruction bin
and execute it.  No compilation, no instruction capture — just DMA the prebuilt
program sections to DRAM and trigger the FPGA.  This is the customer-facing
runner; ship it together with the kernel (`user_dma_core.py`), the config, the
quantized-weights bin (`params.bin` + `params.json`), and `programs.bin` (+ `programs.json`).

  # LM-only
  python3 qwen3.5_2b_run_from_bin.py --prompt "Tell me about the Eiffel Tower."
  # VLM (image caption) — needs the unified bin built by a VLM run of test.py
  python3 qwen3.5_2b_run_from_bin.py --vision-enable
  python3 qwen3.5_2b_run_from_bin.py --image my.jpg --prompt "What is in this image?"

The unified bin holds TWO program sections, BOTH baked for program base
0xD0000000 and run SEQUENTIALLY with a DRAM reset between them:

  [encoder section]  vision encoder  — vision weights + program at base
  [decoder section]  LM decoder      — LM weights    + program at base

VLM order (mandatory): run vision encoder → read merged tokens → reset DRAM →
SINGLE prepare_inference (LM) → LOAD decoder section → prefill + decode.
`prepare_inference` must be called EXACTLY ONCE and AFTER the vision encoder
runs; a second prepare (or vision executed after prepare) silently corrupts the
LM decode.  LM-only skips the encoder entirely.

BOTH program sections are LOADED from the bin — nothing is recompiled.  The
encoder's only compile-time constant (the LayerNorm zeros base) is a shared
`VIS_ZEROS` buffer that `setup_only` seeds on the load path and the kernel reads
via its `ZEROS_DRAM_ADDR` argument — so there is no extra bin section and no
replay step (the encoder would otherwise read stale DRAM → NaN tokens).

The bin is generated by the FIRST VLM run of `qwen3.5_2b_test.py`; this script
only loads it.  All heavy machinery (engine class, prefill/decode, vision
weight upload) is imported from `qwen3.5_2b_test.py` so the two stay in lockstep.
"""
import argparse
import importlib.util
import json
import os
import sys
import time

import torch

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.normpath(os.path.join(_HERE, "..", "..")))  # template root (kernel)
sys.path.insert(0, _HERE)

# The test module's filename has dots, so import it via importlib.
_spec = importlib.util.spec_from_file_location(
    "qwen3_5_2b_test", os.path.join(_HERE, "qwen3.5_2b_test.py"))
T = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(T)

from user_dma_core import DMA_DEVICE_H2C  # noqa: E402

MAX_CONTEXT = 256
TEMPERATURE = 0.0
TOP_K = 0


def _load_program_section(ue, raw: bytes, off: int, size: int) -> int:
    """DMA a program-bin section to the program base (0xD0000000) and return the
    load address.  The section's JUMP_ABS targets were baked for this base."""
    ue.reset_program_dram_addr()
    addr = ue.get_program_dram_addr()
    ue.dma_write(DMA_DEVICE_H2C, addr, raw[off:off + size], size)
    ue.allocate_program_dram(size)
    return addr


def main():
    ap = argparse.ArgumentParser(description="Qwen3.5-2B runtime-only bin runner")
    ap.add_argument("--prompt", type=str, default=None)
    ap.add_argument("--max-new-tokens", type=int, default=64)
    ap.add_argument("--image", type=str, default=None,
                    help="Image path → VLM mode (caption the image).")
    ap.add_argument("--vision-enable", action="store_true",
                    help="VLM mode using the bundled sample image.")
    args = ap.parse_args()

    vision_on = bool(args.image) or args.vision_enable
    _TEST_SAMPLES = os.path.normpath(os.path.join(_HERE, "..", "..", "test_samples"))
    image_path = args.image or (os.path.join(_TEST_SAMPLES, "yosemite.jpg") if args.vision_enable else None)
    if vision_on and image_path and not os.path.exists(image_path):
        raise SystemExit(f"Image file not found: {image_path}")
    if args.prompt is None:
        args.prompt = ("Describe what you see in this image."
                       if vision_on else
                       "Tell me about the Eiffel Tower. What year was it built?")

    script_dir = _HERE
    with open(os.path.join(script_dir, "qwen3.5_2b_config.json")) as f:
        cfg = json.load(f)
    bin_dir = os.path.join(script_dir, "qwen3.5_2b_bin")

    uni_bin  = os.path.join(bin_dir, T.UNIFIED_BIN_NAME)
    uni_meta = os.path.join(bin_dir, T.UNIFIED_META_NAME)
    if not os.path.exists(uni_bin):
        raise SystemExit(
            f"Unified bin not found: {uni_bin}\n"
            f"Generate it first with a VLM run of qwen3.5_2b_test.py "
            f"(e.g. `python3 qwen3.5_2b_test.py --vision-enable --vision-on-hardware`).")
    if not os.path.exists(uni_meta):
        raise SystemExit(f"Unified bin metadata not found: {uni_meta}")
    with open(uni_meta) as f:
        meta = json.load(f)
    with open(uni_bin, "rb") as f:
        raw = f.read()
    print("=" * 78)
    print(f"  Qwen3.5-2B run-from-bin ({'VLM' if vision_on else 'LM'}) — "
          f"{T.UNIFIED_BIN_NAME} ({len(raw)/1024/1024:.2f} MB)")
    print("=" * 78)

    model_dir = T._ensure_hf_model(script_dir, cfg)
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(model_dir, local_files_only=True)
    processor = None
    image = None
    if vision_on:
        from transformers import AutoProcessor
        from PIL import Image
        processor = AutoProcessor.from_pretrained(model_dir, local_files_only=True)
        image = Image.open(image_path).convert("RGB")
        if meta.get("encoder_size", 0) == 0:
            raise SystemExit("Unified bin has no vision-encoder section — rebuild "
                             "it with a --vision-on-hardware run of test.py.")

    weights_path = os.path.join(script_dir, cfg["paths"]["weights_bin"])
    if not os.path.exists(weights_path):
        raise SystemExit(f"Quantized weights not found: {weights_path}")
    weights = torch.load(weights_path,
                         weights_only=False, map_location="cpu")

    print("  FPGA init ...", end=" ", flush=True)
    with T._quiet():
        ue = T.Qwen3_5_2b_UnifiedEngine(device="cpu")
        ue.software_reset()
    print("ok.")

    # ---- VLM: run the vision-encoder section FIRST (before the LM prepare) ----
    precomputed_vision_tokens = None
    if vision_on:
        messages = [{"role": "user", "content": [
            {"type": "image"}, {"type": "text", "text": args.prompt}]}]
        text_for_proc = processor.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True)
        hf_inputs = processor(text=[text_for_proc], images=[image], return_tensors="pt")
        print("  Loading vision encoder from bin ...", flush=True)
        t_v = time.time()
        with T._quiet():
            # LOAD the encoder SECTION from the bin (no rebuild): upload vision
            # weights/inputs (incl. the shared VIS_ZEROS LayerNorm base), DMA the
            # encoder program to base 0xD0000000, and trigger it.  Then reset DRAM
            # so the single prepare_inference (below) places the LM at the same base.
            precomputed_vision_tokens = T.run_vision_from_bin(ue, raw, meta, model_dir, hf_inputs)
            ue.reset_params_dram_addr()
            ue.reset_tensor_dram_addr()
            ue.reset_program_dram_addr()
        print(f"  vision done ({time.time()-t_v:.1f}s, "
              f"{tuple(precomputed_vision_tokens.shape)} merged tokens).")

    # ---- SINGLE prepare_inference (LM), then load the decoder section ----
    with T._quiet():
        ue._preallocate_identity_matrix()
        ue.prepare_inference(weights, max_context=MAX_CONTEXT)
        dec_addr = _load_program_section(ue, raw, meta["decoder_off"], meta["decoder_size"])
        ue._decoder_prog_addr = dec_addr
        ue._decoder_X_dram = meta["decoder_x_dram"]
        ue._decoder_final_norm_dram = meta["decoder_final_norm_dram"]

    # ---- prefill + decode (no compilation; decoder is pre-loaded) ----
    _run_inference(ue, tokenizer, args.prompt, args.max_new_tokens,
                   processor=processor, image=image, model_dir=model_dir,
                   precomputed_vision_tokens=precomputed_vision_tokens)


def _run_inference(ue, tokenizer, prompt, max_new_tokens, processor=None,
                   image=None, model_dir=None, precomputed_vision_tokens=None):
    """Prefill-then-decode using the PRE-LOADED decoder section (mirrors
    qwen3.5_2b_test.generate but skips all compilation)."""
    ids, hf_inputs = T._tokenize_with_chat_template(
        tokenizer, prompt, processor=processor, image=image)
    image_token_id = None
    if hf_inputs is not None:
        image_token_id = int(processor.tokenizer.convert_tokens_to_ids("<|image_pad|>"))
        if precomputed_vision_tokens is None:
            precomputed_vision_tokens = T._run_hf_vision_host(model_dir, hf_inputs)
        print(f"  Using FPGA vision tokens "
              f"({tuple(precomputed_vision_tokens.shape)} merged tokens).")

    T_prompt = int(ids.numel())
    if max_new_tokens <= 0:
        max_new_tokens = ue.max_context - T_prompt
    assert T_prompt + max_new_tokens <= ue.max_context, (
        f"prompt ({T_prompt}) + new ({max_new_tokens}) exceeds max_context={ue.max_context}")

    print("  " + "-" * 74)
    print(f"  PREFILL  (T={T_prompt} prompt tokens)")
    print("  " + "-" * 74)
    # prefill returns the first generated token directly (on-FPGA LM-head argmax
    # of the last prompt token — no host sampling).
    nxt = T.prefill_via_decode(ue, ids, verbose=True,
                               vision_tokens=precomputed_vision_tokens,
                               image_token_id=image_token_id)

    # Clear prefill (T>1) caches before switching to the T=1 decode path.
    ue._primitive_cache.clear()
    ue._rec_cache.clear()
    ue._exec_cache.clear()
    ue._patched_bytes_cache.clear()
    ue._exec_idx = 0

    ue.run_decoder(tokenizer, nxt, max_new_tokens=max_new_tokens,
                   temperature=TEMPERATURE, top_k=TOP_K, verbose=True)


if __name__ == "__main__":
    main()
